# Generated by Django 6.0 on 2025-12-05 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('special', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.TextField(blank=True, null=True)),
                ('hit_type', models.TextField(blank=True, null=True)),
                ('damage', models.TextField(blank=True, null=True)),
                ('startup', models.TextField(blank=True, null=True)),
                ('block', models.TextField(blank=True, null=True)),
                ('hit', models.TextField(blank=True, null=True)),
                ('counter_hit', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frame_data', to='main.characters')),
            ],
        ),
    ]
