# Generated by Django 6.0.3 on 2026-04-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characters',
            options={'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='framedata',
            options={'verbose_name': 'Frame Data', 'verbose_name_plural': 'Frame Data'},
        ),
        migrations.AddField(
            model_name='framedata',
            name='condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='framedata',
            name='move_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
