# Generated by Django 6.0.3 on 2026-04-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_characters_options_alter_framedata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
