# Generated by Django 6.0.3 on 2026-04-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_characters_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framedata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
