# Generated by Django 6.0.3 on 2026-04-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_framedata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='framedata',
            name='BT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='framedata',
            name='BalconyBreak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='framedata',
            name='Bound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='framedata',
            name='FloorBreak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='framedata',
            name='ForceCrouch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='framedata',
            name='Homing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='framedata',
            name='P1_Grounded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='framedata',
            name='P2_Grounded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='framedata',
            name='SS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='framedata',
            name='Throw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='framedata',
            name='WS',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='framedata',
            name='WallBreak',
            field=models.BooleanField(default=False),
        ),
    ]
